### ISSUE TITLE
cant find module

### ISSUE THREAD

**Issue by cahyowhy** [he9qi/ember-cli-emoji#4]
Cannot find module 'D:\cahyo\lumbung-komunitas\lumbung-komunitas-web\bower_components\ember\ember-template-compiler.js'
Error: Cannot find module 'D:\cahyo\lumbung-komunitas\lumbung-komunitas-web\bower_components\ember\ember-template-compiler.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Class.htmlbarsOptions (D:\cahyo\lumbung-komunitas\lumbung-komunitas-web\node_modules\ember-cli-emoji\node_modules\ember-cli-htmlbars\ember-addon-main.js:78:25)
    at Object.toTree (D:\cahyo\lumbung-komunitas\lumbung-komunitas-web\node_modules\ember-cli-emoji\node_modules\ember-cli-htmlbars\ember-addon-main.js:31:36)
    at D:\cahyo\lumbung-komunitas\lumbung-komunitas-web\node_modules\ember-cli-preprocess-registry\preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (D:\cahyo\lumbung-komunitas\lumbung-komunitas-web\node_modules\ember-cli-preprocess-registry\preprocessors.js:178:11)
    at module.exports.preprocessTemplates (D:\cahyo\lumbung-komunitas\lumbung-komunitas-web\node_modules\ember-cli-preprocess-registry\preprocessors.js:161:10)

**Comment by PowerP** [comment]
same here
